add plugin delta tracking
Signed-off-by: Konrad Zawora <kzawora@habana.ai>

diff --git a/.github/workflows/hourly-ci.yaml b/.github/workflows/hourly-ci.yaml
--- a/.github/workflows/hourly-ci.yaml
+++ b/.github/workflows/hourly-ci.yaml
@@ -57,12 +57,12 @@ jobs:
           echo "Looking for commits since: $PREV_RUN_TIME"
           echo "PREV_RUN_TIME=$PREV_RUN_TIME" >> "$GITHUB_OUTPUT"
 
-      - name: List commit differences in the last 4 hours
+      - name: List vLLM commit differences in the last 4 hours
         run: |
           echo "Commits merged/pushed in vllm-project/vllm.git in the last 4 hours:"
           git log HEAD..vllm-upstream/main --pretty=format:"%h - %an, %ar : %s" --since="${{ steps.prev_run_time.outputs.PREV_RUN_TIME }}"
 
-      - name: List commit differences since last stable run
+      - name: List vLLM commit differences since last stable run
         run: |
          LAST_STABLE_VLLM_COMMIT=$(git show origin/vllm/last-good-commit-for-vllm-gaudi:VLLM_STABLE_COMMIT)
          if [ $? -ne 0 ]; then
@@ -77,6 +77,22 @@ jobs:
          echo "Last stable vLLM commit: $LAST_STABLE_VLLM_COMMIT_TITLE"
          echo "Commits merged/pushed in vllm-project/vllm.git since last stable commit:"
          git log $LAST_STABLE_VLLM_COMMIT..vllm-upstream/main --pretty=format:"%h - %an, %ar : %s"
+
+      - name: List vLLM-Gaudi commit differences since last stable run
+        run: |
+         LAST_STABLE_VLLM_GAUDI_COMMIT=$(git show origin/vllm/last-good-commit-for-vllm-gaudi:VLLM_GAUDI_STABLE_COMMIT)
+         if [ $? -ne 0 ]; then
+          echo "ERROR: No VLLM_GAUDI_STABLE_COMMIT file found in origin/vllm/last-good-commit-for-vllm-gaudi."
+          exit 1
+         fi
+         LAST_STABLE_VLLM_GAUDI_COMMIT_TITLE=$(git show --no-patch --oneline $LAST_STABLE_VLLM_GAUDI_COMMIT)
+         if [ $? -ne 0 ]; then
+          echo "ERROR: VLLM_GAUDI_STABLE_COMMIT contents does not look like a valid vLLM-Gaudi commit"
+          exit 1
+         fi 
+         echo "Last stable vLLM commit: $LAST_STABLE_VLLM_GAUDI_COMMIT_TITLE"
+         echo "Commits merged/pushed in vllm-project/vllm-gaudi.git since last stable commit:"
+         git log $LAST_STABLE_VLLM_GAUDI_COMMIT..${{ github.sha }} --pretty=format:"%h - %an, %ar : %s"
 
       - name: Get latest commit sha from vllm-upstream/main
         id: latest_vllm_commit
