add unit tests as dependency for pre_merge_hpu_test
Signed-off-by: Konrad Zawora <kzawora@habana.ai>

diff --git a/.github/workflows/pre-merge.yaml b/.github/workflows/pre-merge.yaml
--- a/.github/workflows/pre-merge.yaml
+++ b/.github/workflows/pre-merge.yaml
@@ -73,27 +73,6 @@ jobs:
 
           EOF
           echo "Docker image built successfully."
-  pre_merge_hpu_test:
-    runs-on: ucb-vllm-cicd-g2
-    needs: pre_merge_hpu_test_build
-    steps:
-      - name: Run test scripts
-        run: |
-          EXITCODE=1
-          remove_docker_containers() { docker rm -f hpu-plugin-v1-test-pre-merge || true; }
-          trap 'remove_docker_containers; exit $EXITCODE;' EXIT
-          remove_docker_containers
-
-          echo "Running HPU plugin v1 test"
-          docker run --rm --runtime=habana --name=hpu-plugin-v1-test-pre-merge --network=host \
-            -e HABANA_VISIBLE_DEVICES=all \
-            -e HF_HOME=/workspace/hf_cache \
-            -v /mnt/hf_cache:/workspace/hf_cache \
-            hpu-plugin-v1-test-env-pre-merge \
-            /bin/bash "/workspace/vllm-gaudi/tests/full_tests/ci_gsm8k_tests.sh"
-          
-          EXITCODE=$?
-          echo "Test script exited with code: $EXITCODE"
   hpu_unit_tests:
     runs-on: ucb-vllm-cicd-g2
     needs: pre_merge_hpu_test_build
@@ -115,3 +94,28 @@ jobs:
           
           EXITCODE=$?
           echo "Test script exited with code: $EXITCODE"
+
+  pre_merge_hpu_test:
+    runs-on: ucb-vllm-cicd-g2
+    # This is a final job that runs after the build and unit tests 
+    # Unit tests are supposed to fail fast if anything goes wrong, removing the need for this job to run.
+    needs: [pre_merge_hpu_test_build, hpu_unit_tests]
+    steps:
+      - name: Run test scripts
+        run: |
+          EXITCODE=1
+          remove_docker_containers() { docker rm -f hpu-plugin-v1-test-pre-merge || true; }
+          trap 'remove_docker_containers; exit $EXITCODE;' EXIT
+          remove_docker_containers
+
+          echo "Running HPU plugin v1 test"
+          docker run --rm --runtime=habana --name=hpu-plugin-v1-test-pre-merge --network=host \
+            -e HABANA_VISIBLE_DEVICES=all \
+            -e HF_HOME=/workspace/hf_cache \
+            -v /mnt/hf_cache:/workspace/hf_cache \
+            hpu-plugin-v1-test-env-pre-merge \
+            /bin/bash "/workspace/vllm-gaudi/tests/full_tests/ci_gsm8k_tests.sh"
+          
+          EXITCODE=$?
+          echo "Test script exited with code: $EXITCODE"
+
