last one
Signed-off-by: Chendi Xue <Chendi.Xue@intel.com>

diff --git a/.github/workflows/pre-merge.yaml b/.github/workflows/pre-merge.yaml
--- a/.github/workflows/pre-merge.yaml
+++ b/.github/workflows/pre-merge.yaml
@@ -1,7 +1,7 @@
 name: Basic HPU test suite 
 
 on:
-  pull_request:
+  pull_request_target:
     types: [opened, synchronize, reopened, ready_for_review]
     branches: [main]
 
@@ -330,142 +330,141 @@ jobs:
           EOF
           echo "Docker image built successfully."
 
-  # hpu_unit_tests:
-  #   runs-on: ucb-vllm-cicd-g2
-  #   needs: pre_merge_hpu_test_build
-  #   steps:
-  #     - name: Run pytest in tests/unit_tests
-  #       run: |
-  #         EXITCODE=1
-  #         remove_docker_containers() { docker rm -f hpu-plugin-v1-test-unit-tests-${{ github.event.pull_request.head.sha }} || true; }
-  #         trap 'remove_docker_containers; exit $EXITCODE;' EXIT
-  #         remove_docker_containers
+  hpu_unit_tests:
+    runs-on: ucb-vllm-cicd-g2
+    needs: pre_merge_hpu_test_build
+    steps:
+      - name: Run pytest in tests/unit_tests
+        run: |
+          EXITCODE=1
+          remove_docker_containers() { docker rm -f hpu-plugin-v1-test-unit-tests-${{ github.event.pull_request.head.sha }} || true; }
+          trap 'remove_docker_containers; exit $EXITCODE;' EXIT
+          remove_docker_containers
 
-  #         echo "Running HPU plugin v1 unit tests"
-  #         docker run --rm --runtime=habana --name=hpu-plugin-v1-test-unit-tests-${{ github.event.pull_request.head.sha }} --network=host \
-  #           -e HABANA_VISIBLE_DEVICES=all \
-  #           -e HF_HOME=/workspace/hf_cache \
-  #           -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
-  #           -v /mnt/hf_cache:/workspace/hf_cache \
-  #           hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
-  #           /bin/bash -c "pytest -vvv --durations=10 --durations-min=1.0 /workspace/vllm-gaudi/tests/unit_tests"
+          echo "Running HPU plugin v1 unit tests"
+          docker run --rm --runtime=habana --name=hpu-plugin-v1-test-unit-tests-${{ github.event.pull_request.head.sha }} --network=host \
+            -e HABANA_VISIBLE_DEVICES=all \
+            -e HF_HOME=/workspace/hf_cache \
+            -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
+            -v /mnt/hf_cache:/workspace/hf_cache \
+            hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
+            /bin/bash -c "pytest -vvv --durations=10 --durations-min=1.0 /workspace/vllm-gaudi/tests/unit_tests"
           
-  #         EXITCODE=$?
-  #         echo "Test script exited with code: $EXITCODE"
-  # hpu_pd_tests:
-  #   runs-on: ucb-vllm-cicd-g2
-  #   # This is a final job that runs after the build and unit tests 
-  #   # Unit tests are supposed to fail fast if anything goes wrong, removing the need for this job to run.
-  #   needs: [pre_merge_hpu_test_build, hpu_unit_tests]
-  #   steps:
-  #     - name: Run test scripts
-  #       run: |
-  #         EXITCODE=1
-  #         remove_docker_containers() { docker rm -f hpu-plugin-v1-test-pd-tests-${{ github.event.pull_request.head.sha }} || true; }
-  #         trap 'remove_docker_containers; exit $EXITCODE;' EXIT
-  #         remove_docker_containers
+          EXITCODE=$?
+          echo "Test script exited with code: $EXITCODE"
+  hpu_pd_tests:
+    runs-on: ucb-vllm-cicd-g2
+    # This is a final job that runs after the build and unit tests 
+    # Unit tests are supposed to fail fast if anything goes wrong, removing the need for this job to run.
+    needs: [pre_merge_hpu_test_build, hpu_unit_tests]
+    steps:
+      - name: Run test scripts
+        run: |
+          EXITCODE=1
+          remove_docker_containers() { docker rm -f hpu-plugin-v1-test-pd-tests-${{ github.event.pull_request.head.sha }} || true; }
+          trap 'remove_docker_containers; exit $EXITCODE;' EXIT
+          remove_docker_containers
 
-  #         echo "Running HPU plugin v1 nixl pd tests"
-  #         docker run --rm --runtime=habana --name=hpu-plugin-v1-test-pd-tests-${{ github.event.pull_request.head.sha }} --network=host \
-  #           -e HABANA_VISIBLE_DEVICES=all \
-  #           -e HF_HOME=/workspace/hf_cache \
-  #           -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
-  #           -v /mnt/hf_cache:/workspace/hf_cache \
-  #           hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
-  #           /bin/bash -c "
-  #               pip install nixl==0.5.0 lm-eval[api] &&
-  #               cd /workspace/vllm-gaudi/tests/unit_tests &&
-  #               ./run_accuracy_test.sh
-  #           "
+          echo "Running HPU plugin v1 nixl pd tests"
+          docker run --rm --runtime=habana --name=hpu-plugin-v1-test-pd-tests-${{ github.event.pull_request.head.sha }} --network=host \
+            -e HABANA_VISIBLE_DEVICES=all \
+            -e HF_HOME=/workspace/hf_cache \
+            -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
+            -v /mnt/hf_cache:/workspace/hf_cache \
+            hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
+            /bin/bash -c "
+                pip install nixl==0.5.0 lm-eval[api] &&
+                cd /workspace/vllm-gaudi/tests/unit_tests &&
+                ./run_accuracy_test.sh
+            "
 
-  #         EXITCODE=$?
-  #         echo "Test script exited with code: $EXITCODE"
-  # hpu_perf_tests:
-  #   runs-on: ucb-vllm-cicd-g2
-  #   # This is a final job that runs after the build and unit tests 
-  #   # Unit tests are supposed to fail fast if anything goes wrong, removing the need for this job to run.
-  #   needs: [pre_merge_hpu_test_build, hpu_unit_tests]
-  #   steps:
-  #     - name: Run test scripts
-  #       run: |
-  #         EXITCODE=1
-  #         remove_docker_containers() { docker rm -f hpu-plugin-v1-test-perf-tests-${{ github.event.pull_request.head.sha }} || true; }
-  #         trap 'remove_docker_containers; exit $EXITCODE;' EXIT
-  #         remove_docker_containers
+          EXITCODE=$?
+          echo "Test script exited with code: $EXITCODE"
+  hpu_perf_tests:
+    runs-on: ucb-vllm-cicd-g2
+    # This is a final job that runs after the build and unit tests 
+    # Unit tests are supposed to fail fast if anything goes wrong, removing the need for this job to run.
+    needs: [pre_merge_hpu_test_build, hpu_unit_tests]
+    steps:
+      - name: Run test scripts
+        run: |
+          EXITCODE=1
+          remove_docker_containers() { docker rm -f hpu-plugin-v1-test-perf-tests-${{ github.event.pull_request.head.sha }} || true; }
+          trap 'remove_docker_containers; exit $EXITCODE;' EXIT
+          remove_docker_containers
 
-  #         echo "Running HPU plugin v1 perf tests"
-  #         docker run --rm --runtime=habana --name=hpu-plugin-v1-test-perf-tests-${{ github.event.pull_request.head.sha }} --network=host \
-  #           -e HABANA_VISIBLE_DEVICES=all \
-  #           -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
-  #           -e HF_HOME=/workspace/hf_cache \
-  #           -v /mnt/hf_cache:/workspace/hf_cache \
-  #           hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
-  #           /bin/bash "/workspace/vllm-gaudi/tests/full_tests/ci_perf_tests.sh"
+          echo "Running HPU plugin v1 perf tests"
+          docker run --rm --runtime=habana --name=hpu-plugin-v1-test-perf-tests-${{ github.event.pull_request.head.sha }} --network=host \
+            -e HABANA_VISIBLE_DEVICES=all \
+            -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
+            -e HF_HOME=/workspace/hf_cache \
+            -v /mnt/hf_cache:/workspace/hf_cache \
+            hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
+            /bin/bash "/workspace/vllm-gaudi/tests/full_tests/ci_perf_tests.sh"
           
-  #         EXITCODE=$?
-  #         echo "Test script exited with code: $EXITCODE"
-  # hpu_dp_tests:
-  #   runs-on: ucb-vllm-cicd-g2
-  #   # This is a final job that runs after the build and unit tests 
-  #   # Unit tests are supposed to fail fast if anything goes wrong, removing the need for this job to run.
-  #   needs: [pre_merge_hpu_test_build, hpu_unit_tests]
-  #   steps:
-  #     - name: Run test scripts
-  #       run: |
-  #         EXITCODE=1
-  #         remove_docker_containers() { docker rm -f hpu-plugin-v1-test-dp-tests-${{ github.event.pull_request.head.sha }} || true; }
-  #         trap 'remove_docker_containers; exit $EXITCODE;' EXIT
-  #         remove_docker_containers
+          EXITCODE=$?
+          echo "Test script exited with code: $EXITCODE"
+  hpu_dp_tests:
+    runs-on: ucb-vllm-cicd-g2
+    # This is a final job that runs after the build and unit tests 
+    # Unit tests are supposed to fail fast if anything goes wrong, removing the need for this job to run.
+    needs: [pre_merge_hpu_test_build, hpu_unit_tests]
+    steps:
+      - name: Run test scripts
+        run: |
+          EXITCODE=1
+          remove_docker_containers() { docker rm -f hpu-plugin-v1-test-dp-tests-${{ github.event.pull_request.head.sha }} || true; }
+          trap 'remove_docker_containers; exit $EXITCODE;' EXIT
+          remove_docker_containers
 
-  #         echo "Running HPU plugin v1 dp tests"
-  #         docker run --rm --runtime=habana --name=hpu-plugin-v1-test-dp-tests-${{ github.event.pull_request.head.sha }} --network=host \
-  #           -e HABANA_VISIBLE_DEVICES=all \
-  #           -e HF_HOME=/workspace/hf_cache \
-  #           -e VLLM_SKIP_WARMUP=true \
-  #           -e PT_HPU_LAZY_MODE=1 \
-  #           -e VLLM_USE_V1=1 \
-  #           -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
-  #           -v /mnt/hf_cache:/workspace/hf_cache \
-  #           hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
-  #           /bin/bash -c "python -u /workspace/vllm-gaudi/examples/data_parallel.py --dp-size 2 --tp-size 2"
+          echo "Running HPU plugin v1 dp tests"
+          docker run --rm --runtime=habana --name=hpu-plugin-v1-test-dp-tests-${{ github.event.pull_request.head.sha }} --network=host \
+            -e HABANA_VISIBLE_DEVICES=all \
+            -e HF_HOME=/workspace/hf_cache \
+            -e VLLM_SKIP_WARMUP=true \
+            -e PT_HPU_LAZY_MODE=1 \
+            -e VLLM_USE_V1=1 \
+            -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
+            -v /mnt/hf_cache:/workspace/hf_cache \
+            hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
+            /bin/bash -c "python -u /workspace/vllm-gaudi/examples/data_parallel.py --dp-size 2 --tp-size 2"
 
-  #         EXITCODE=$?
-  #         echo "Test script exited with code: $EXITCODE"
-  # e2e:
-  #   runs-on: ucb-vllm-cicd-g2
-  #   needs: [pre_merge_hpu_test_build, hpu_unit_tests, discover_tests]
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       # The list of test functions is dynamically populated from the output of the 'discover_tests' job.
-  #       test_function: ${{ fromJson(needs.discover_tests.outputs.matrix) }}
+          EXITCODE=$?
+          echo "Test script exited with code: $EXITCODE"
+  e2e:
+    runs-on: ucb-vllm-cicd-g2
+    needs: [pre_merge_hpu_test_build, hpu_unit_tests, discover_tests]
+    strategy:
+      fail-fast: false
+      matrix:
+        # The list of test functions is dynamically populated from the output of the 'discover_tests' job.
+        test_function: ${{ fromJson(needs.discover_tests.outputs.matrix) }}
 
-  #   steps:
-  #     - name: Run test suite - ${{ matrix.test_function }}
-  #       run: |
-  #         EXITCODE=1
-  #         CONTAINER_NAME="hpu-plugin-test-e2e-${{ github.event.pull_request.head.sha }}-${{ matrix.test_function }}"
-  #         # Ensure the container is removed upon exit, regardless of success or failure.
-  #         remove_docker_containers() { docker rm -f $CONTAINER_NAME || true; }
-  #         trap 'remove_docker_containers; exit $EXITCODE;' EXIT
-  #         remove_docker_containers
+    steps:
+      - name: Run test suite - ${{ matrix.test_function }}
+        run: |
+          EXITCODE=1
+          CONTAINER_NAME="hpu-plugin-test-e2e-${{ github.event.pull_request.head.sha }}-${{ matrix.test_function }}"
+          # Ensure the container is removed upon exit, regardless of success or failure.
+          remove_docker_containers() { docker rm -f $CONTAINER_NAME || true; }
+          trap 'remove_docker_containers; exit $EXITCODE;' EXIT
+          remove_docker_containers
 
-  #         echo "Running HPU plugin test: ${{ matrix.test_function }}"
-  #         docker run --rm --runtime=habana --name=$CONTAINER_NAME --network=host \
-  #           -e HABANA_VISIBLE_DEVICES=all \
-  #           -e HF_HOME=/workspace/hf_cache \
-  #           -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
-  #           -v /mnt/hf_cache:/workspace/hf_cache \
-  #           hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
-  #           /bin/bash "/workspace/vllm-gaudi/tests/full_tests/ci_gsm8k_tests.sh" "${{ matrix.test_function }}"
+          echo "Running HPU plugin test: ${{ matrix.test_function }}"
+          docker run --rm --runtime=habana --name=$CONTAINER_NAME --network=host \
+            -e HABANA_VISIBLE_DEVICES=all \
+            -e HF_HOME=/workspace/hf_cache \
+            -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
+            -v /mnt/hf_cache:/workspace/hf_cache \
+            hpu-plugin-v1-test-env-pre-merge-${{ github.event.pull_request.head.sha }} \
+            /bin/bash "/workspace/vllm-gaudi/tests/full_tests/ci_gsm8k_tests.sh" "${{ matrix.test_function }}"
 
-  #         EXITCODE=$?
-  #         echo "Test script exited with code: $EXITCODE"
+          EXITCODE=$?
+          echo "Test script exited with code: $EXITCODE"
   
   pre_merge_hpu_test:
     runs-on: ucb-vllm-cicd-g2
-    needs: [pre_merge_hpu_test_build]
-    #needs: [hpu_unit_tests, e2e, hpu_perf_tests]
+    needs: [hpu_unit_tests, e2e, hpu_perf_tests]
     # This job is required to pass for pre-merge CI. By itself it does nothing, and will only pass if all jobs specified in "needs" list pass.
     steps:
       - name: Succeeded if all previous jobs passed
